theme: just-the-docs
title: etqiu.github.io
search_enabled: false
color_scheme: light
sass:
  sass_dir: _sass
description: I'm currently a freshman studying data science at UC Berkeley. I'm also interested in studying Natural Language Processing and neural networks, especially learning more about using sci-kit learn and tensorflow.
url: https://etqiu.github.io

collections:
  projects:
    output: true
  timeline: 
    output: true
  