theme: just-the-docs
title: etqiu.github.io
search_enabled: false
color_scheme: light

aux_links:
  "Dark Mode":
    - "#"
  # You can add other links here too, like:
  # "GitHub":
  #   - "//github.com/yourusername/yourrepo"

aux_links_new_tab: false  # Set to true if you want links to open in new tab

# Add these attributes to the aux links
aux_links_attributes:
  "Dark Mode":
    aria-label: "Dark Mode"
